pref("extensions.ankifox.dicname1", "Dictionary 1");
pref("extensions.ankifox.dicname2", "Dictionary 2");
pref("extensions.ankifox.dicname3", "Dictionary 3");
pref("extensions.ankifox.dicname4", "Dictionary 4");
pref("extensions.ankifox.dic1", "http://m.dictionary.com/definition/%s?linkid=ibc5yn&srcpage=home&site=dictwap");
pref("extensions.ankifox.dic2", "http://www.wordreference.com/es/translation.asp?tranword=%s");
pref("extensions.ankifox.dic3", "http://en.bab.la/dictionary/english-spanish/%s");
pref("extensions.ankifox.dic4", "https://translate.google.com/m?hl=es&sl=en&tl=es&ie=UTF-8&prev=_m&q=%s");
pref("extensions.ankifox.use-dic", "0");
pref("extensions.ankifox.notetype", "");
pref("extensions.ankifox.deckname", "");